# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac1d19b6785a090153230a445fc6128744337a919cbb461f1f1ed7e88c2c942139fbb003885446a8283daec476200a7b5d19380d004d04480a44310feb95dfd2

test:
  secret_key_base: 052c050fa669371df9c5a0c4e9c6340eaa4f78be858375380fe04cedafa488c023e36635eb6d2047f1f3b00372632152bf9757628203c60502cbb2d180f78146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
